config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :manufacturers
  resources :customers do
    get 'search', on: :collection
  end
  resources :car_categories
  resources :subsidiaries
  resources :car_models, only: [:index, :show, :new, :create]
  resources :rentals, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
    #get 'start', on: :member
    #post 'init', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :car_model
  has_many :car_rentals
  has_many :rentals, through: :car_rentals

end

app/models/car_category.rb
class CarCategory < ApplicationRecord
  has_many :car_models
  has_many :cars, through: :car_models
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :manufacturer
  belongs_to :car_category
  has_many :cars
  validates :name, :year, :motorization, :fuel_type, presence: true
end

app/models/car_rental.rb
class CarRental < ApplicationRecord
  belongs_to :car
  belongs_to :rental
  belongs_to :user
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :rentals
  scope :search, ->(query) { where('name LIKE ?', "%#{query}%")
                              .or(where(document: query)) }
  #def search(query)
    #where('name LIKE ?', "%#{query}%")
  #end
  #validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :car_models
  validates :name, uniqueness: { message: 'Nome deve ser único' }
  validates :name, presence: { message: 'Nome não pode ficar em branco' }
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :customer
  belongs_to :car_category
  has_one :car_rental
  has_one :car, through: :car_rental

  before_create :generate_code
  
  enum status: { scheduled: 0, ongoing: 5 }
  
  private
  
  def generate_code
    self.code = SecureRandom.alphanumeric(6).upcase
  end
end

app/models/subsidiary.rb
class Subsidiary < ApplicationRecord
  validates :name, :cnpj, :adress, presence: true
  validates :name, :adress, uniqueness: true
  validates :cnpj, format: { with: /\A^\d{2,3}\.\d{3}\.\d{3}\/\d{4}\-\d{2}$\z/, message: 'não é válido' }
  validate :cnpj_must_be_valid

  private

  def cnpj_must_be_valid
    return if CNPJ.valid?(cnpj, strict:true)

    errors.add(:cnpj, 'não é válido')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  #enum role: { user: 0, admin: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
end

app/controllers/car_categories_controller.rb
class CarCategoriesController < ApplicationController
  def index
    @car_categories = CarCategory.all
  end

  def show
    @car_category = CarCategory.find(params[:id])
    #@car_models = CarModel.where(car_category: @car_category)
  end

  def new
    @car_category = CarCategory.new
  end

  def create
    @car_category = CarCategory.new(params.require(:car_category).permit(:name, :daily_rate, :car_insurance, :third_party_insurance))
    @car_category.save
    redirect_to car_category_path(CarCategory.last.id)
  end

end

app/controllers/car_models_controller.rb
class CarModelsController < ApplicationController
  def index
    @car_models = CarModel.all
  end

  def show
    @car_model = CarModel.find(params[:id])
  end

  def new
    @car_model = CarModel.new
    @manufacturers = Manufacturer.all
    @car_categories = CarCategory.all
  end

  def create
    @car_model = CarModel.new(params.require(:car_model).permit(:name, :motorization,
    :year, :fuel_type, :manufacturer_id, :car_category_id))
    if @car_model.save
      redirect_to @car_model
    else
      @manufacturers = Manufacturer.all
      @car_categories = CarCategory.all
      render :new
    end
  end

  private


end

app/controllers/car_rentals_controller.rb
class CarRentalsController < ApplicationController
  def new
    @rental = Rental.find(params[:rental_id])
    @car_rental = CarRental.new
    @cars = @rental.car_category.cars
  end

  def create
    @rental = Rental.find(params[:rental_id])
    @car_rental = CarRental.new(params.require(:car_rental).permit(:car_id))
    @car_rental.user = current_user
    @car_rental.rental = @rental
    @car_rental.save!
    @rental.ongoing!
    #@car.unavailable!

    redirect_to @rental
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(params.require(:customer).permit(:name, :document, :email))
    @customer.save
    redirect_to customer_path(Customer.last.id)
  end

  def search
    #@customers = Customer.where('name LIKE ?', "%#{params[:q]}%")
    @customers = Customer.search(params[:q])
    render :index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  #before_action :set_manufacturer, only [:]

  def index
    @manufacturers = Manufacturer.all  
  end

  def show
    id = params[:id]
    @manufacturer = Manufacturer.find(id)
  end

  def new
    @manufacturer = Manufacturer.new
  end
  
  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    if @manufacturer.save
      flash[:notice] = 'Fabricante criado com sucesso'
      redirect_to @manufacturer
    else
      render :new
    end
  end
  
  def edit
    @manufacturer = Manufacturer.find(params[:id])
  end
  # PATCH ou PUT
  def update
    @manufacturer = Manufacturer.find(params[:id])
    if @manufacturer.update(manufacturer_params)
      redirect_to @manufacturer
    else
      render :edit
    end
  end

  def destroy
    @manufacturer = Manufacturer.find(params[:id])
    @manufacturer.destroy
    redirect_to manufacturers_path
  end

  private

  def set_manufacturer
    @manufacturer = Manufacturer.find(params[:id])
  end

  def manufacturer_params
    params.require(:manufacturer).permit(:name)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create]
  #TODO :fechar rotas de get com teste 
  def index
    @rentals = Rental.all
  end
  
  def new
    @rental = Rental.new
    @customers = Customer.all
    @car_categories = CarCategory.all
  end

  def create
    @rental = Rental.create(params.require(:rental).permit(:start_date, 
                                                           :end_date, 
                                                           :customer_id, 
                                                           :car_category_id))
    RentalsMailer.scheduled(@rental).deliver_now
    redirect_to rentals_path
  end

  def search
    @q = params[:q]
    @rental = Rental.find_by(code: @q.upcase)
    # if @rental.blank? || params[:q].blank? 
    #   @rentals = Rental.all
    #   flash.now[:alert] = "Nenhum resultado encontrado para: #{@q}"
    #   render :index
    # end
  end

  def show
    @rental = Rental.find(params[:id])
  end

end

app/controllers/subsidiaries_controller.rb
class SubsidiariesController < ApplicationController
  #before_action :authenticate_user!
  #before_action :authorize_admin
  #before_action :set_subsidiary, only: %i[show edit update]

  def index
    @subsidiaries = Subsidiary.all
  end

  def show
    @subsidiary = Subsidiary.find(params[:id])
  end

  def new
    @subsidiary = Subsidiary.new
  end

  def create
    @subsidiary = Subsidiary.new(params.require(:subsidiary).permit(:name, :cnpj, :adress))
    return redirect_to @subsidiary if @subsidiary.save

    render :new
  end

  # def set_subsidiary
  #   @subsidiary = Subisidiary.find(params[:id])
  # end

  # def authorize_admin
  #   redirect_to root_path, notice: 'Não autorizado' unless current_user.admin?
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/car_categories/index.html.erb
<h1>Categorias de carros</h1>
<% if CarCategory.count == 0 %>
  <p> Nenhuma categoria cadastrada <p>
<% end %>
<% @car_categories.each do |c| %>
  <div>
    <h2><%= link_to "Categoria #{c.name}", c %></h2>
    <dl>
      <dt>Valor da Diária</dt>
      <dd><%= number_to_currency c.daily_rate%></dd>
    </dl>
  </div>
<% end %>
<%= link_to 'Voltar', root_path %>
<%= link_to 'Registrar categoria', new_car_category_path %>

app/views/car_categories/new.html.erb
<%= form_for @car_category do |c| %>
  <%= c.label :name, 'Nome' %>
  <%= c.text_field :name %>
  <%= c.label :daily_rate, 'Taxa Diaria' %>
  <%= c.text_field :daily_rate %>
  <%= c.label :car_insurance, 'Seguro' %>
  <%= c.text_field :car_insurance %>
  <%= c.label :third_party_insurance, 'Seguro de terceiros' %>
  <%= c.text_field :third_party_insurance %>
  <%= c.submit 'Enviar' %>
<% end %>

app/views/car_categories/show.html.erb
<section>
  <header>
    <h1>Categoria <%= @car_category.name %></h1>
  </header>
  <p> Detalhes </p>
  <dl>
    <dt>Diária:</dt>
    <dd><%= number_to_currency @car_category.daily_rate %></dd>
    <dt>Seguro do Carro:</dt>
    <dd><%= number_to_currency @car_category.car_insurance %></dd>
    <dt>Seguro para terceiros:</dt>
    <dd><%= number_to_currency @car_category.third_party_insurance %></dd>
  </dl>

  <h3>Modelos de carro</h3>
  <% @car_category.car_models.each do |car_model| %>
    <%= link_to car_model.name, car_model %>
  <% end %>
  <%= link_to 'Voltar', car_categories_path %>
</section>

app/views/car_models/index.html.erb
<h1>Modelos de Carros</h1>

<%= link_to 'Registrar modelo de carro', new_car_model_path %>

<table>
  <thead>
    <tr>
      <th>Fabricante</th>
      <th>Nome</th>
      <th>Ano</th>
      <th></th> 
    </tr>
  </thead>
  <tbody>
    <% @car_models.each do |cm| %>
      <tr id="car-model-<%= cm.id %>">
        <td><%= cm.manufacturer.name %></td>
        <td><%= cm.name %></td>
        <td><%= cm.year %></td>
        <td><%= link_to 'Ver Detalhes', cm, id: "details-#{cm.id}" %>
    </tr>
    <% end %>
  </tbody> 
</table>

app/views/car_models/new.html.erb
<h1>Novo modelo de carro</h1>

<% if @car_model.errors.any? %>
  <ul>
    <% @car_model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @car_model, local: true do |f| %>
  <div>
    <strong><%= f.label :name %></strong>
    <%= f.text_field :name %>
  </div>
  <div>
    <strong><%= f.label :year %></strong>
    <%= f.number_field :year, value: Time.zone.now.year.to_s %>
  </div>
  <div>
    <strong><%= f.label :motorization %></strong>
    <%= f.text_field :motorization %>
  </div>
  <div>
    <strong><%= f.label :fuel_type %></strong>
    <%= f.text_field :fuel_type %>
  </div>
  <div>
    <strong><%= f.label :manufacturer_id %></strong>
    <%= f.collection_select :manufacturer_id, @manufacturers, :id, :name %>
  </div>
  <div>
    <strong><%= f.label :car_category_id %></strong>
    <%= f.collection_select :car_category_id, @car_categories, :id, :name %>
  </div>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/car_models/show.html.erb
<section id="main">
  <h1>Modelo de Carro <%= @car_model.name %></h1>
  <dl>
    <dt><%= CarModel.human_attribute_name(:manufacturer) %>: </dt>
    <dd><%= @car_model.manufacturer.name %></dd>
    <dt>Ano: </dt>
    <dd><%= @car_model.year %></dd>
    <dt>Motor: </dt>
    <dd><%= @car_model.motorization %></dd>
    <dt>Combustível: </dt>
    <dd><%= @car_model.fuel_type%>
    <dt>Categoria: </dt>
    <dd><%= @car_model.car_category.name %></dd>
    <dt>Diária: </dt>
    <dd><%= number_to_currency @car_model.car_category.daily_rate %></dd> 
  </dl>
</section>

app/views/car_rentals/new.html.erb
<%= form_with model: [@rental, @car_rental], local: true do |f| %>
  <%= f.label :car_id, 'Carro' %>
  <%= f.collection_select :car_id, @cars, :id, :license_plate %>
  <%= f.submit 'Confirmar locação' %>
<% end %>

app/views/customers/index.html.erb
<h1>Clientes</h1>

<%= link_to 'Registrar novo cliente', new_customer_path %>

<%= form_with url: search_customers_path, method: :get, local: true do |f|  %>
  <%= f.label :q, 'Busca' %>
  <%= f.search_field :q %>
  <%= f.submit 'Buscar' %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Documento</th>
      <th></th> 
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr id="customer-<%= customer.id %>">
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.document %></td>
    </tr>
    <% end %>
  </tbody> 
</table>

app/views/customers/new.html.erb
<%= form_for @customer do |c| %>
  <%= c.label :name, 'Nome' %>
  <%= c.text_field :name %>
  <%= c.label :document, 'CPF' %>
  <%= c.text_field :document %>
  <%= c.label :email, 'E-mail' %>
  <%= c.text_field :email %>
  <%= c.submit 'Enviar' %>
<% end %>

app/views/customers/show.html.erb
<h1><%= @customer.name %></h1>
<p> Detalhes </p>
<ul>
  <li>CPF: <%= @customer.document %></li>
  <li>E-mail: <%= @customer.email%></li>
</ul>
<%= link_to 'Voltar', customers_path %>

<table>
  <tr>
    <th><%= Rental.human_attribute_name(:code) %></th>
    <th><%= Rental.human_attribute_name(:start_date) %></th>
    <th><%= Rental.human_attribute_name(:end_date) %></th>
    <th><%= Rental.human_attribute_name(:car_category) %></th>
    <th><%= Rental.human_attribute_name(:status) %></th>
    <th>Ações</th>
  </tr>
  <% @customer.rentals.each do |rental| %>
    <tr id="rental-<%= rental.code %>">
      <td><%= rental.code %></td>
      <td><%= l rental.start_date %></td>
      <td><%= l rental.end_date %></td>
      <td><%= rental.car_category.name %></td>
      <td><%= Rental.human_attribute_name("status.#{rental.status}") %></td>
      <td>
        <% if rental.scheduled? %>
          <%= link_to 'Iniciar', new_rental_car_rental_path(rental) %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/home/index.html.erb
<header>
  <h1>Rental Cars</h1>
  <h2>Bem vindo ao sistema de gestão de locação</h2>
</header>

<h3>Playground do i18n</h3>

<p><%= I18n.translate('hello') %></p>

<%= I18n.localize(Time.zone.now) %>
<br>
<%= I18n.localize(Date.today)%>
<br>
<%= distance_of_time_in_words(12000) %>
<br>
<%= number_to_currency(990)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentalCars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
        <%-# current.admin? %>
        <%= link_to 'Filiais', subsidiaries_path %>
        <% #end %>
        <%= link_to 'Locações', rentals_path %>
        <%= link_to 'Categorias de carros', car_categories_path %>
        <%= link_to 'Clientes', customers_path %>
        <%= link_to 'Fabricantes', manufacturers_path %>
        <%= link_to 'Modelos de Carros', car_models_path%>
        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Entrar', new_user_session_path %>
      <% end %>  
    </nav>
    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <%= yield %>
  </body>
</html>

app/views/manufacturers/edit.html.erb
<h1>Editar um fabricante</h1>

<% @manufacturer.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with(model: @manufacturer, local: true) do |m| %>
  <%= m.label :name, 'Nome' %>
  <%= m.text_field :name %>
  <%= m.submit 'Enviar' %>
<% end %>

app/views/manufacturers/index.html.erb
<h1>Fabricantes</h1>

<%= link_to 'Registrar novo fabricante', new_manufacturer_path %>

<% if Manufacturer.count == 0 %>
  <p> Nenhum fabricante cadastrado <p>
<% end %>
<ul>
  <% @manufacturers.each do |m| %>
    <li><%= link_to m.name, manufacturer_path(id: m.id) %></li>
  <% end %>
</ul>
<%= link_to 'Voltar', root_path %>

app/views/manufacturers/new.html.erb
<h1>Registrar fabricante</h1>

<% @manufacturer.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_for @manufacturer do |m| %>
  <%= m.label :name, 'Nome' %>
  <%= m.text_field :name %>
  <%= m.submit 'Enviar' %>
<% end %>

app/views/manufacturers/show.html.erb
<h1><%= @manufacturer.name %></h1>

<%= link_to 'Editar', edit_manufacturer_path(@manufacturer) %>
<%= link_to 'Apagar fabricante', manufacturer_path(id: @manufacturer.id), method: :delete %>
<%= link_to 'Voltar', manufacturers_path %>

app/views/rentals/_rental.html.erb
<dl>
  <dt><%= Rental.human_attribute_name(:code) %></dt>
  <dd><%= rental.code %></dd>
  <dt>Data de início:</dt>
  <dd><%= l rental.start_date %></dd>
  <dt>Data de término:</dt>
  <dd><%= l rental.end_date %></dd>
  <dt>Cliente:</dt>
  <dd><%= rental.customer.name %></dd>
  <dt>Categoria:</dt>
  <dd><%= rental.car_category.name %></dd>
  <dt>Status:</dt>
  <dd><%= Rental.human_attribute_name("status.#{rental.status}") %></dd>
</dl>

app/views/rentals/index.html.erb
<h1>Locações</h1>

<%= link_to 'Registrar nova locação', new_rental_path %>

<%= form_with url: search_rentals_path, method: :get do |f| %>
  <%= f.label :q, 'Código' %>
  <%= f.text_field :q %>
  <%= f.submit 'Buscar' %>
<% end %>

<%= render @rentals %>

app/views/rentals/new.html.erb
<h1>Nova locação</h1>

<%= form_with model: @rental, local: true do |f| %>
  <%= f.label :start_date, 'Data de início' %>
  <%= f.date_field :start_date %>
  <%= f.label :end_date, 'Data de término' %>
  <%= f.date_field :end_date %>
  <%= f.label :customer_id, 'Cliente' %>
  <%= f.collection_select :customer_id, @customers, :id, :name %>
  <%= f.label :car_category_id, 'Categoria' %>
  <%= f.collection_select :car_category_id, @car_categories, :id, :name %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/rentals/search.html.erb
<% if @rental %>
  <dl>
    <dt>Código</dt>
    <dd><%= @rental.code %></dd>
    <dt>Data de início:</dt>
    <dd><%= l @rental.start_date %></dd>
    <dt>Data de término:</dt>
    <dd><%= l @rental.end_date %></dd>
    <dt>Cliente:</dt>
    <dd><%= @rental.customer.name %></dd>
    <dt>Categoria:</dt>
    <dd><%= @rental.car_category.name %></dd>
  </dl>
  <%= link_to 'Iniciar', new_rental_car_rental_path(@rental) %>
<% else %>
  <p><%= "Nenhum resultado encontrado para: #{@q}" %></p>
<% end %>

app/views/rentals/show.html.erb
<%= render @rental %>


<% if @rental.car_rental.present? %>
  <p>Data de início da locação: <%= l @rental.car_rental.created_at, format: :long %></p>
  <p>Carro: <%= @rental.car_rental.car.license_plate %></p>
  <p>Cliente: <%= @rental.customer.email %></p>
  <p>Locação iniciado por: <%= @rental.car_rental.user.email %></p>
<% end %>

app/views/subsidiaries/index.html.erb
<h1>Filiais</h1>
<% if Subsidiary.count == 0 %>
  <p> Nenhuma filial cadastrada <p>
<% end %>
<ul>
  <% @subsidiaries.each do |s| %>
    <li><%= link_to s.name, subsidiary_path(id: s.id) %></li>
  <% end %>
</ul>
<%= link_to 'Voltar', root_path %>
<%= link_to 'Registrar filial', new_subsidiary_path %>

app/views/subsidiaries/new.html.erb
<%= form_for @subsidiary do |s| %>
  <%= s.label :name, 'Nome' %>
  <%= s.text_field :name %>
  <%= s.label :cnpj, 'CNPJ'%>
  <%= s.text_field :cnpj %>
  <%= s.label :adress, 'Endereço'%>
  <%= s.text_field :adress %>
  <%= s.submit 'Enviar' %>
<% end %>

app/views/subsidiaries/show.html.erb
<h1><%= @subsidiary.name %></h1>
<p> Detalhes </p>
<ul>
  <li>CNPJ <%= @subsidiary.cnpj %></li>
  <li>Endereço: <%= @subsidiary.adress%></li>
</ul>
<%= link_to 'Voltar', subsidiaries_path %>